---
- hosts: web
  become: yes
  remote_user: ubuntu
  vars:
    - dir_name: test

  vars_prompt:
    - name: password
      prompt: What is your password ?
      private: false


  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: creat dir 
      file:
        path: "{{ dir_name }}"
        state: directory 

    - name: 
      command: " ls {{ dir_name }} "
