---
- hosts: web
  become: yes
  remote_user: ubuntu
  vars:
    - dir_name: test
    - myname: omar

  vars_prompt:
    - name: password
      prompt: What is your password ?
      private: false


  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: creat dir 
      file:
        path: "{{ dir_name }}"
        state: directory 

    - name: 
      command: " ls {{ dir_name }} "
      register: result 

    - name: print stdout 
      debug: 
        var: result.stdout
    - name: copy tamplate
      template:
        scr: myconfig.j2
        dest: myconfig
